### ISSUE TITLE
Used with hapi-swagger together display  "Missing views manager"

### ISSUE THREAD

**Issue by terranc** [dwyl/hapi-error#60]
![image](https://user-images.githubusercontent.com/224353/45589250-39548800-b955-11e8-9673-c7a8249ee9f4.png)

**Comment by nelsonic** [comment]
This error is due to `hapi-error` having the _core_ purpose of human-friendly error _pages_ (AKA views).
`hapi-swagger` https://github.com/glennjones/hapi-swagger is for API Documentation.

The "fix" (_workaround_) for using `hapi-swagger` with `hapi-error` is to simply add `views` directive to your app as shown in the example:
https://github.com/dwyl/hapi-error/blob/f32a99fa7800d7f35144e030898feb75ec0230be/example/server_example.js#L10-L15

`hapi-swagger` already includes `handlebars` https://github.com/glennjones/hapi-swagger/blob/38008da0f6d3c248fc63d761bd44ef17a3e3a4f1/package.json#L53 so you won't be adding any _unnecessary_ dependencies to your project. 

Hope that helps anyone `else` facing a similar issue. 💭 

Closing _this_ issue due to inactivity. ⏳ 
Please re-open if still having trouble (_and add more detail_). 👍
